### ISSUE TITLE
Rename API token, consider localStorage

### ISSUE THREAD

**Issue by mricos** [bhopper197/plan-by-plate#12]
This is the one and only place the Zomato API is used. Perhaps rename to indicate this is the Zomato API.  Rather than global, consider localStorage which is more natural place to get your global data. Model function could useful here, e,g, getZomatoApi(). Not completely necessary but I'd like for you to be thinking about interfaces (functions that get and set) rather than using global variables.

https://github.com/bhopper197/plan-by-plate/blob/c9a3966079cc872d770ff0b24a350bf7807159d3/index.js#L141

**Comment by bhopper197** [comment]
I can see what you're saying. The whole purpose is to get in this mindset of setting and getting.
