### ISSUE TITLE
Semantic v. Syntax

### ISSUE THREAD

**Issue by mricos** [bhopper197/plan-by-plate#2]
toggleModal refers to visual syntax. Maybe rename to toggleModalWhatItRepresents to add semantics to the name of the function.

https://github.com/bhopper197/plan-by-plate/blob/c9a3966079cc872d770ff0b24a350bf7807159d3/index.js#L29

**Comment by bhopper197** [comment]
Changed the function name to **_toggleModalAddedRestaurant(event)_**. As it gives more definition to what modal is being toggled.
