### ISSUE TITLE
Good place of a story-telling comment.

### ISSUE THREAD

**Issue by mricos** [bhopper197/plan-by-plate#4]
When telling code-stories based around a function, good place to start is the function signature's input. What is input plates? 

 https://github.com/bhopper197/plan-by-plate/blob/c9a3966079cc872d770ff0b24a350bf7807159d3/index.js#L29

**Comment by bhopper197** [comment]
Where in the code are you referencing? the code snippet seems to be stuck on the one from an earlier issue.
