### ISSUE TITLE
Type of plates

### ISSUE THREAD

**Issue by mricos** [bhopper197/plan-by-plate#6]
Is plate an Object or an Array? Typically we map over an Array an not an Object. It is possible to map over an Object's keys but mapping is typically over an array.

 https://github.com/bhopper197/plan-by-plate/blob/c9a3966079cc872d770ff0b24a350bf7807159d3/index.js#L29

**Comment by bhopper197** [comment]
The **plates** is an array, not an object. If you debug the mapPlateList() and you can see the typeOf **plates** is an array.
